export const initialState = {
  categories: ["Task", "RandomThought", "Idea"],
  archivedNotes: [],
  archivedVisibility: false,
  status: {
    active: {},
    archived: {},
  },
  notes: [
    {
      name: "Shopping list",
      created: "April 20, 2021",
      category: "Task",
      content: "Tomatoes, bread",
      dates: "",
      isArchived: false,
      editable: false,
    },
    {
      name: "The theory of evolutions",
      created: "April 27, 2021",
      category: "RandomThought",
      content: "the evolution of the strongest..",
      dates: "",
      isArchived: false,
      editable: false,
    },
    {
      name: "New Feature",
      created: "May 05, 2021",
      category: "Idea",
      content: "Implement new...",
      dates: "3/5/2021, 05.05.2021",
      isArchived: false,
      editable: false,
    },
    {
      name: "William Gaddis",
      created: "May 07, 2021",
      category: "Idea",
      content: "Power doesn't co..",
      dates: "",
      isArchived: false,
      editable: false,
    },
    {
      name: "Books",
      created: "May 15, 2021",
      category: "Task",
      content: "The Lean Startup",
      dates: "",
      isArchived: false,
      editable: false,
    },
  ],
};
